### ISSUE TITLE
including moodle core profile fields

### ISSUE THREAD

**Issue by AnnieHy** [moodle-an-hochschulen/moodle-local_profilecohort#58]
Is it also possible to integrate the moodle standard profile fields such as e-mail or Institution to make a profile field based assignment to global groups?

**Comment by christianwolters** [comment]
Hi @AnnieHy,

thank you for taking your time to create this issue.

As you can see, we haven't added any new features in a while and
the maintaining team will discuss whether we want to continue developing this plugin.

The reason is that it may not be worth continuing to maintain a this plugin if there's already a better alternative.
Please take a look at this plugin, which might be a better fit for both your needs and ours
https://moodle.org/plugins/tool_dynamic_cohorts

Cheers
Christian

**Comment by christianwolters** [comment]
I'll close this issue for now.

**Comment by AnnieHy** [comment]
Hi Christian,

thank you for your response. I´ll have a look at above plugin you mentioned.
best wishes
Andrea
