### ISSUE TITLE
Improvement: Text consistency at the beginning and end

### ISSUE THREAD

**Issue by stdoma** [moodle-an-hochschulen/moodle-local_profilecohort#59]
Hello!
It would be good if you can check a text match at the beginning and at the end of a string.

Often you can work with checking a match or the availability of a substring.
Because of organizational reasons we have to concatenate several items of information in one field. We are lucky that all partial information are unique. This means that the check at the beginning and end is not absolutely necessary.

In general, it would be a profitable improvement.

**Comment by christianwolters** [comment]
Hi @stdoma,

thank you for taking your time to create this issue.

As you can see, we haven't added any new features in a while and
the maintaining team will discuss whether we want to continue developing this plugin.

The reason is that it may not be worth continuing to maintain a this plugin if there's already a better alternative.
Please take a look at this plugin, which might be a better fit for both your needs and ours
https://moodle.org/plugins/tool_dynamic_cohorts

Cheers
Christian

PS: Closing this for now.
