### ISSUE TITLE
Some Users are skipped

### ISSUE THREAD

**Issue by phodder63** [moodle-an-hochschulen/moodle-local_profilecohort#60]
We have set up a profile field base cohort that is based off of two checkbox style profile fields.  The rules are set up to assign users to a cohort if value 1 is "No" and value 2 is "Yes".  The rule works for a vast majority of the users (3600+), but we have found there is a subset (35) of users that are not added.  Of the 35 users, we verified that none are suspended or deleted.  We also reviewed their login activity and nearly all of them had recent logins.  We also reviewed mdl_user.lastlogin and mdl_user.timemodified and determined that many had very recently logged in or changed their account profile; two of the events that should trigger cohort membership (in addition to the regularly scheduled task that updates the cohort).

**Comment by christianwolters** [comment]
Hi @phodder63,

thank you for taking your time to create this issue.

As you can see, we haven't added any new features in a while and
the maintaining team will discuss whether we want to continue developing this plugin.

The reason is that it may not be worth continuing to maintain a this plugin if there's already a better alternative.
Please take a look at this plugin, which might be a better fit for both your needs and ours
https://moodle.org/plugins/tool_dynamic_cohorts

Cheers
Christian

PS: Closing this for now.
