### ISSUE TITLE
Rules are only applied, when user was manually updated, not when created or logged in

### ISSUE THREAD

**Issue by Poe2024** [moodle-an-hochschulen/moodle-local_profilecohort#61]
I can't seem to get the Plug-In to work and I have no idea why that could be. I created a profile field, assigning every user to an organisation and then created the rule, that every user in the organisation should be in a cohort. No user was assigned.

When I clicked on a single user and updated the profile, they would then be assidned to the cohort. But when a new user is created or a user logs in, they are not assigned. Only after being manually updated, which of yourse defeats the purpose of the Plug-In automatically managing the cohorts.
Is there anything I can do to fix this issue. I would really appreciate the help.

**Comment by christianwolters** [comment]
Hi @Poe2024 

thank you for taking your time to create this issue.

As you can see, we haven't added any new features in a while and we wanted to let you know that
the maintaining team will discuss whether we want to continue developing this plugin.

The reason is that it may not be worth continuing to maintain a this plugin if there's already a better alternative.
Please take a look at this plugin, which might be a better fit for both your needs and ours
https://moodle.org/plugins/tool_dynamic_cohorts

Cheers
Christian

PS: Closing this for now.
