### ISSUE TITLE
Some cohorts not available

### ISSUE THREAD

**Issue by hhsfantasma** [moodle-an-hochschulen/moodle-local_profilecohort#67]
I want to assign our Grade 10, 11 and 12 students to grade cohorts named Grade 10 students, Grade 11 students and Grade 12 students using a profile field named profile_field_Grade. This works perfectly for 11 and 12, but generates an error for Grade 10.
![Grade10](https://github.com/user-attachments/assets/66274637-61fa-420a-a566-798489e830ed)

I also want to add some Grade 8 students to a class cohort named 8MM and some Grade 9 students to a class cohort named 9MM. The Grade 8MM works perfectly, but 9MM does not appear in the Matches list when I try to add a new rule for it. If I rename 9MM to 9MX, it still does not appear in the Matches list. 9MM is a managed cohort. I have tried deleting the 9MM cohort and then recreating it, but to no avail.

**Comment by christianwolters** [comment]
Hi @hhsfantasma,

thank you for taking your time to create this issue.

As you can see, we haven't added any new features in a while and we wanted to let you know that
the maintaining team will discuss whether we want to continue developing this plugin.

The reason is that it may not be worth continuing to maintain a this plugin if there's already a better alternative.
Please take a look at this plugin, which might be a better fit for both your needs and ours
https://moodle.org/plugins/tool_dynamic_cohorts

Cheers
Christian

PS: Closing this for now.
